version: '3.8'

services:
  mongo:
    image: mongo:6.0.13
    container_name: mongo
    ports:
      - "27017:27017"

  fastapi:
    build: ./backend
    container_name: fastapi
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
